# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsperMatch.ui'
#
# Created: Thu May 28 14:01:50 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InsperMatch(object):
    def setupUi(self, InsperMatch):
        InsperMatch.setObjectName(_fromUtf8("InsperMatch"))
        InsperMatch.resize(1097, 561)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        InsperMatch.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Pictures/raposa atlética.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InsperMatch.setWindowIcon(icon)
        self.mdiArea = QtGui.QMdiArea(InsperMatch)
        self.mdiArea.setGeometry(QtCore.QRect(940, 10, 131, 151))
        self.mdiArea.setFrameShape(QtGui.QFrame.Box)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayoutWidget = QtGui.QWidget(InsperMatch)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 234, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout.addWidget(self.radioButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(InsperMatch)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 266, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateEdit = QtGui.QDateEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1990, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(InsperMatch)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 601, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit = QtGui.QTextEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.comboBox = QtGui.QComboBox(InsperMatch)
        self.comboBox.setGeometry(QtCore.QRect(10, 150, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(InsperMatch)
        self.label_4.setGeometry(QtCore.QRect(10, 510, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_2 = QtGui.QComboBox(InsperMatch)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 510, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, _fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(InsperMatch)
        self.pushButton.setGeometry(QtCore.QRect(850, 510, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_2 = QtGui.QGroupBox(InsperMatch)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 171, 311))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 98, 301))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_12 = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.verticalLayout_5.addWidget(self.checkBox_12)
        self.checkBox_9 = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.verticalLayout_5.addWidget(self.checkBox_9)
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.checkBox_11 = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.verticalLayout_5.addWidget(self.checkBox_11)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_5.addWidget(self.checkBox)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(80, 10, 93, 301))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox_13 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.verticalLayout_6.addWidget(self.checkBox_13)
        self.checkBox_14 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.verticalLayout_6.addWidget(self.checkBox_14)
        self.checkBox_15 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.verticalLayout_6.addWidget(self.checkBox_15)
        self.checkBox_16 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.verticalLayout_6.addWidget(self.checkBox_16)
        self.checkBox_17 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.verticalLayout_6.addWidget(self.checkBox_17)
        self.checkBox_24 = QtGui.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.verticalLayout_6.addWidget(self.checkBox_24)
        self.groupBox_3 = QtGui.QGroupBox(InsperMatch)
        self.groupBox_3.setGeometry(QtCore.QRect(200, 180, 201, 311))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 115, 301))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBox_18 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.verticalLayout_7.addWidget(self.checkBox_18)
        self.checkBox_10 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.verticalLayout_7.addWidget(self.checkBox_10)
        self.checkBox_7 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.verticalLayout_7.addWidget(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.verticalLayout_7.addWidget(self.checkBox_8)
        self.checkBox_19 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.verticalLayout_7.addWidget(self.checkBox_19)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_7.addWidget(self.checkBox_2)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(120, 10, 91, 301))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.checkBox_20 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.verticalLayout_8.addWidget(self.checkBox_20)
        self.checkBox_21 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.verticalLayout_8.addWidget(self.checkBox_21)
        self.checkBox_22 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.verticalLayout_8.addWidget(self.checkBox_22)
        self.checkBox_23 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.verticalLayout_8.addWidget(self.checkBox_23)
        self.checkBox_25 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.verticalLayout_8.addWidget(self.checkBox_25)
        self.checkBox_26 = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.verticalLayout_8.addWidget(self.checkBox_26)
        self.groupBox_4 = QtGui.QGroupBox(InsperMatch)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 180, 161, 311))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayoutWidget_15 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 72, 301))
        self.verticalLayoutWidget_15.setObjectName(_fromUtf8("verticalLayoutWidget_15"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.checkBox_61 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.verticalLayout_15.addWidget(self.checkBox_61)
        self.checkBox_62 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.verticalLayout_15.addWidget(self.checkBox_62)
        self.checkBox_63 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_63.setObjectName(_fromUtf8("checkBox_63"))
        self.verticalLayout_15.addWidget(self.checkBox_63)
        self.checkBox_64 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.verticalLayout_15.addWidget(self.checkBox_64)
        self.checkBox_65 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_65.setObjectName(_fromUtf8("checkBox_65"))
        self.verticalLayout_15.addWidget(self.checkBox_65)
        self.checkBox_66 = QtGui.QCheckBox(self.verticalLayoutWidget_15)
        self.checkBox_66.setObjectName(_fromUtf8("checkBox_66"))
        self.verticalLayout_15.addWidget(self.checkBox_66)
        self.verticalLayoutWidget_16 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(80, 10, 72, 301))
        self.verticalLayoutWidget_16.setObjectName(_fromUtf8("verticalLayoutWidget_16"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.checkBox_67 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_67.setObjectName(_fromUtf8("checkBox_67"))
        self.verticalLayout_16.addWidget(self.checkBox_67)
        self.checkBox_68 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_68.setObjectName(_fromUtf8("checkBox_68"))
        self.verticalLayout_16.addWidget(self.checkBox_68)
        self.checkBox_69 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_69.setObjectName(_fromUtf8("checkBox_69"))
        self.verticalLayout_16.addWidget(self.checkBox_69)
        self.checkBox_70 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_70.setObjectName(_fromUtf8("checkBox_70"))
        self.verticalLayout_16.addWidget(self.checkBox_70)
        self.checkBox_71 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_71.setObjectName(_fromUtf8("checkBox_71"))
        self.verticalLayout_16.addWidget(self.checkBox_71)
        self.checkBox_72 = QtGui.QCheckBox(self.verticalLayoutWidget_16)
        self.checkBox_72.setObjectName(_fromUtf8("checkBox_72"))
        self.verticalLayout_16.addWidget(self.checkBox_72)
        self.groupBox_5 = QtGui.QGroupBox(InsperMatch)
        self.groupBox_5.setGeometry(QtCore.QRect(610, 180, 211, 311))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayoutWidget_19 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(20, 10, 78, 301))
        self.verticalLayoutWidget_19.setObjectName(_fromUtf8("verticalLayoutWidget_19"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.checkBox_85 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_85.setObjectName(_fromUtf8("checkBox_85"))
        self.verticalLayout_19.addWidget(self.checkBox_85)
        self.checkBox_86 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_86.setObjectName(_fromUtf8("checkBox_86"))
        self.verticalLayout_19.addWidget(self.checkBox_86)
        self.checkBox_87 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_87.setObjectName(_fromUtf8("checkBox_87"))
        self.verticalLayout_19.addWidget(self.checkBox_87)
        self.checkBox_88 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_88.setObjectName(_fromUtf8("checkBox_88"))
        self.verticalLayout_19.addWidget(self.checkBox_88)
        self.checkBox_89 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_89.setObjectName(_fromUtf8("checkBox_89"))
        self.verticalLayout_19.addWidget(self.checkBox_89)
        self.checkBox_90 = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.checkBox_90.setObjectName(_fromUtf8("checkBox_90"))
        self.verticalLayout_19.addWidget(self.checkBox_90)
        self.verticalLayoutWidget_20 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(120, 10, 82, 301))
        self.verticalLayoutWidget_20.setObjectName(_fromUtf8("verticalLayoutWidget_20"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.checkBox_91 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_91.setObjectName(_fromUtf8("checkBox_91"))
        self.verticalLayout_20.addWidget(self.checkBox_91)
        self.checkBox_92 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_92.setObjectName(_fromUtf8("checkBox_92"))
        self.verticalLayout_20.addWidget(self.checkBox_92)
        self.checkBox_93 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_93.setObjectName(_fromUtf8("checkBox_93"))
        self.verticalLayout_20.addWidget(self.checkBox_93)
        self.checkBox_94 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_94.setObjectName(_fromUtf8("checkBox_94"))
        self.verticalLayout_20.addWidget(self.checkBox_94)
        self.checkBox_95 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_95.setObjectName(_fromUtf8("checkBox_95"))
        self.verticalLayout_20.addWidget(self.checkBox_95)
        self.checkBox_96 = QtGui.QCheckBox(self.verticalLayoutWidget_20)
        self.checkBox_96.setObjectName(_fromUtf8("checkBox_96"))
        self.verticalLayout_20.addWidget(self.checkBox_96)
        self.groupBox_6 = QtGui.QGroupBox(InsperMatch)
        self.groupBox_6.setGeometry(QtCore.QRect(850, 180, 231, 311))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayoutWidget_23 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(10, 10, 153, 301))
        self.verticalLayoutWidget_23.setObjectName(_fromUtf8("verticalLayoutWidget_23"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_23.setMargin(0)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.checkBox_109 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_109.setObjectName(_fromUtf8("checkBox_109"))
        self.verticalLayout_23.addWidget(self.checkBox_109)
        self.checkBox_110 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_110.setObjectName(_fromUtf8("checkBox_110"))
        self.verticalLayout_23.addWidget(self.checkBox_110)
        self.checkBox_111 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_111.setObjectName(_fromUtf8("checkBox_111"))
        self.verticalLayout_23.addWidget(self.checkBox_111)
        self.checkBox_112 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_112.setObjectName(_fromUtf8("checkBox_112"))
        self.verticalLayout_23.addWidget(self.checkBox_112)
        self.checkBox_113 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_113.setObjectName(_fromUtf8("checkBox_113"))
        self.verticalLayout_23.addWidget(self.checkBox_113)
        self.checkBox_114 = QtGui.QCheckBox(self.verticalLayoutWidget_23)
        self.checkBox_114.setObjectName(_fromUtf8("checkBox_114"))
        self.verticalLayout_23.addWidget(self.checkBox_114)
        self.verticalLayoutWidget_24 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(160, 10, 73, 301))
        self.verticalLayoutWidget_24.setObjectName(_fromUtf8("verticalLayoutWidget_24"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_24.setMargin(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.checkBox_115 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_115.setObjectName(_fromUtf8("checkBox_115"))
        self.verticalLayout_24.addWidget(self.checkBox_115)
        self.checkBox_116 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_116.setObjectName(_fromUtf8("checkBox_116"))
        self.verticalLayout_24.addWidget(self.checkBox_116)
        self.checkBox_117 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_117.setObjectName(_fromUtf8("checkBox_117"))
        self.verticalLayout_24.addWidget(self.checkBox_117)
        self.checkBox_118 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_118.setObjectName(_fromUtf8("checkBox_118"))
        self.verticalLayout_24.addWidget(self.checkBox_118)
        self.checkBox_119 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_119.setObjectName(_fromUtf8("checkBox_119"))
        self.verticalLayout_24.addWidget(self.checkBox_119)
        self.checkBox_120 = QtGui.QCheckBox(self.verticalLayoutWidget_24)
        self.checkBox_120.setObjectName(_fromUtf8("checkBox_120"))
        self.verticalLayout_24.addWidget(self.checkBox_120)

        self.retranslateUi(InsperMatch)
        QtCore.QMetaObject.connectSlotsByName(InsperMatch)

    def retranslateUi(self, InsperMatch):
        InsperMatch.setWindowTitle(_translate("InsperMatch", "InperMatch", None))
        self.label_3.setText(_translate("InsperMatch", "Sexo:", None))
        self.radioButton_2.setText(_translate("InsperMatch", "Masculino", None))
        self.radioButton.setText(_translate("InsperMatch", "Feminino", None))
        self.label_2.setText(_translate("InsperMatch", "Data de Nascimento:", None))
        self.label.setText(_translate("InsperMatch", "Nome:", None))
        self.comboBox.setItemText(0, _translate("InsperMatch", "Curso", None))
        self.comboBox.setItemText(1, _translate("InsperMatch", "Engenharia", None))
        self.comboBox.setItemText(2, _translate("InsperMatch", "Administração", None))
        self.comboBox.setItemText(3, _translate("InsperMatch", "Economia", None))
        self.label_4.setText(_translate("InsperMatch", "Bairro:", None))
        self.comboBox_2.setItemText(1, _translate("InsperMatch", "Água Rasa", None))
        self.comboBox_2.setItemText(2, _translate("InsperMatch", "Alto de Pinheiros", None))
        self.comboBox_2.setItemText(3, _translate("InsperMatch", "Alphaville", None))
        self.comboBox_2.setItemText(4, _translate("InsperMatch", "Anhanguera", None))
        self.comboBox_2.setItemText(5, _translate("InsperMatch", "Aricanduva", None))
        self.comboBox_2.setItemText(6, _translate("InsperMatch", "Artur Alvim", None))
        self.comboBox_2.setItemText(7, _translate("InsperMatch", "Barra Funda", None))
        self.comboBox_2.setItemText(8, _translate("InsperMatch", "Bela Vista", None))
        self.comboBox_2.setItemText(9, _translate("InsperMatch", "Belém", None))
        self.comboBox_2.setItemText(10, _translate("InsperMatch", "Bom Retiro", None))
        self.comboBox_2.setItemText(11, _translate("InsperMatch", "Brasilândia", None))
        self.comboBox_2.setItemText(12, _translate("InsperMatch", "Butantã", None))
        self.comboBox_2.setItemText(13, _translate("InsperMatch", "Cachoeirinha", None))
        self.comboBox_2.setItemText(14, _translate("InsperMatch", "Cambuci", None))
        self.comboBox_2.setItemText(15, _translate("InsperMatch", "Campo Belo", None))
        self.comboBox_2.setItemText(16, _translate("InsperMatch", "Campo Grande", None))
        self.comboBox_2.setItemText(17, _translate("InsperMatch", "Campo Limpo", None))
        self.comboBox_2.setItemText(18, _translate("InsperMatch", "Cangaíba", None))
        self.comboBox_2.setItemText(19, _translate("InsperMatch", "Capão Redondo", None))
        self.comboBox_2.setItemText(20, _translate("InsperMatch", "Carrão", None))
        self.comboBox_2.setItemText(21, _translate("InsperMatch", "Cidade Ademar", None))
        self.comboBox_2.setItemText(22, _translate("InsperMatch", "Cidade Dutra", None))
        self.comboBox_2.setItemText(23, _translate("InsperMatch", "Cidade líder", None))
        self.comboBox_2.setItemText(24, _translate("InsperMatch", "Cidade Tiradentes", None))
        self.comboBox_2.setItemText(25, _translate("InsperMatch", "Consolação", None))
        self.comboBox_2.setItemText(26, _translate("InsperMatch", "Cursino", None))
        self.comboBox_2.setItemText(27, _translate("InsperMatch", "Emerlino Matarazzo", None))
        self.comboBox_2.setItemText(28, _translate("InsperMatch", "Freguesia do Ó", None))
        self.comboBox_2.setItemText(29, _translate("InsperMatch", "Grajaú", None))
        self.comboBox_2.setItemText(30, _translate("InsperMatch", "Guaianases", None))
        self.comboBox_2.setItemText(31, _translate("InsperMatch", "Iguatemi", None))
        self.comboBox_2.setItemText(32, _translate("InsperMatch", "Ipiranga", None))
        self.comboBox_2.setItemText(33, _translate("InsperMatch", "Itaim Bibi", None))
        self.comboBox_2.setItemText(34, _translate("InsperMatch", "Itaim Paulista", None))
        self.comboBox_2.setItemText(35, _translate("InsperMatch", "Itaquera", None))
        self.comboBox_2.setItemText(36, _translate("InsperMatch", "Jabaquara", None))
        self.comboBox_2.setItemText(37, _translate("InsperMatch", "Jaçanã", None))
        self.comboBox_2.setItemText(38, _translate("InsperMatch", "Jaguará", None))
        self.comboBox_2.setItemText(39, _translate("InsperMatch", "Jardim Helena", None))
        self.comboBox_2.setItemText(40, _translate("InsperMatch", "Jardim Paulista", None))
        self.comboBox_2.setItemText(41, _translate("InsperMatch", "Jardim São Luís", None))
        self.comboBox_2.setItemText(42, _translate("InsperMatch", "Lapa", None))
        self.comboBox_2.setItemText(43, _translate("InsperMatch", "Liberdade", None))
        self.comboBox_2.setItemText(44, _translate("InsperMatch", "Limão", None))
        self.comboBox_2.setItemText(45, _translate("InsperMatch", "Mandaqui", None))
        self.comboBox_2.setItemText(46, _translate("InsperMatch", "Marsilac", None))
        self.comboBox_2.setItemText(47, _translate("InsperMatch", "Moema", None))
        self.comboBox_2.setItemText(48, _translate("InsperMatch", "Mooca", None))
        self.comboBox_2.setItemText(49, _translate("InsperMatch", "Morumbi", None))
        self.comboBox_2.setItemText(50, _translate("InsperMatch", "Parelheiros", None))
        self.comboBox_2.setItemText(51, _translate("InsperMatch", "Pari", None))
        self.comboBox_2.setItemText(52, _translate("InsperMatch", "Parque do Carmo", None))
        self.comboBox_2.setItemText(53, _translate("InsperMatch", "Pedreira", None))
        self.comboBox_2.setItemText(54, _translate("InsperMatch", "Penha", None))
        self.comboBox_2.setItemText(55, _translate("InsperMatch", "Perdizes", None))
        self.comboBox_2.setItemText(56, _translate("InsperMatch", "Pinheiros", None))
        self.comboBox_2.setItemText(57, _translate("InsperMatch", "Pirituba", None))
        self.comboBox_2.setItemText(58, _translate("InsperMatch", "Ponte Rasa", None))
        self.comboBox_2.setItemText(59, _translate("InsperMatch", "Raposo Tavares", None))
        self.comboBox_2.setItemText(60, _translate("InsperMatch", "República", None))
        self.comboBox_2.setItemText(61, _translate("InsperMatch", "Rio Pequeno", None))
        self.comboBox_2.setItemText(62, _translate("InsperMatch", "Sacomã", None))
        self.comboBox_2.setItemText(63, _translate("InsperMatch", "Santa Cecília", None))
        self.comboBox_2.setItemText(64, _translate("InsperMatch", "Santana", None))
        self.comboBox_2.setItemText(65, _translate("InsperMatch", "Santo Amaro", None))
        self.comboBox_2.setItemText(66, _translate("InsperMatch", "São Domingos", None))
        self.comboBox_2.setItemText(67, _translate("InsperMatch", "São Lucas", None))
        self.comboBox_2.setItemText(68, _translate("InsperMatch", "São Mateus", None))
        self.comboBox_2.setItemText(69, _translate("InsperMatch", "São Miguel Paulista", None))
        self.comboBox_2.setItemText(70, _translate("InsperMatch", "São Rafael", None))
        self.comboBox_2.setItemText(71, _translate("InsperMatch", "Sapopemba", None))
        self.comboBox_2.setItemText(72, _translate("InsperMatch", "Saúde", None))
        self.comboBox_2.setItemText(73, _translate("InsperMatch", "Sé", None))
        self.comboBox_2.setItemText(74, _translate("InsperMatch", "Tatuapé", None))
        self.comboBox_2.setItemText(75, _translate("InsperMatch", "Tremembé", None))
        self.comboBox_2.setItemText(76, _translate("InsperMatch", "Tucuruvi", None))
        self.comboBox_2.setItemText(77, _translate("InsperMatch", "Vila Andrade", None))
        self.comboBox_2.setItemText(78, _translate("InsperMatch", "Vila Curuça", None))
        self.comboBox_2.setItemText(79, _translate("InsperMatch", "Vila Formosa", None))
        self.comboBox_2.setItemText(80, _translate("InsperMatch", "Vila Guilherme", None))
        self.comboBox_2.setItemText(81, _translate("InsperMatch", "Vila Jacuí", None))
        self.comboBox_2.setItemText(82, _translate("InsperMatch", "Vila Leopoldina", None))
        self.comboBox_2.setItemText(83, _translate("InsperMatch", "Vila Maria", None))
        self.comboBox_2.setItemText(84, _translate("InsperMatch", "Vila Mariana", None))
        self.comboBox_2.setItemText(85, _translate("InsperMatch", "Vila Matilde", None))
        self.comboBox_2.setItemText(86, _translate("InsperMatch", "Vila Medeiros", None))
        self.comboBox_2.setItemText(87, _translate("InsperMatch", "Vila Prudente", None))
        self.comboBox_2.setItemText(88, _translate("InsperMatch", "Vila Sônia", None))
        self.pushButton.setText(_translate("InsperMatch", "Salvar", None))
        self.groupBox_2.setTitle(_translate("InsperMatch", "Esportes", None))
        self.checkBox_12.setText(_translate("InsperMatch", "Futebol", None))
        self.checkBox_9.setText(_translate("InsperMatch", "Futsal", None))
        self.checkBox_5.setText(_translate("InsperMatch", "Vôlei", None))
        self.checkBox_6.setText(_translate("InsperMatch", "Handebol", None))
        self.checkBox_11.setText(_translate("InsperMatch", "Jiu-Jitsu", None))
        self.checkBox.setText(_translate("InsperMatch", "Judô", None))
        self.checkBox_13.setText(_translate("InsperMatch", "Rugby", None))
        self.checkBox_14.setText(_translate("InsperMatch", "Natação", None))
        self.checkBox_15.setText(_translate("InsperMatch", "Basquete", None))
        self.checkBox_16.setText(_translate("InsperMatch", "Tênis de Mesa", None))
        self.checkBox_17.setText(_translate("InsperMatch", "Tênis", None))
        self.checkBox_24.setText(_translate("InsperMatch", "Xadrez", None))
        self.groupBox_3.setTitle(_translate("InsperMatch", "Preferências", None))
        self.checkBox_18.setText(_translate("InsperMatch", "Balada", None))
        self.checkBox_10.setText(_translate("InsperMatch", "Ler um Livro", None))
        self.checkBox_7.setText(_translate("InsperMatch", "Role no Shopping", None))
        self.checkBox_8.setText(_translate("InsperMatch", "Ficar em Casa", None))
        self.checkBox_19.setText(_translate("InsperMatch", "Tirar uma Soneca", None))
        self.checkBox_2.setText(_translate("InsperMatch", "Passear no Parque", None))
        self.checkBox_20.setText(_translate("InsperMatch", "Concerto", None))
        self.checkBox_21.setText(_translate("InsperMatch", "Teatro", None))
        self.checkBox_22.setText(_translate("InsperMatch", "Show", None))
        self.checkBox_23.setText(_translate("InsperMatch", "Bar", None))
        self.checkBox_25.setText(_translate("InsperMatch", "Cinema", None))
        self.checkBox_26.setText(_translate("InsperMatch", "Stand-Up", None))
        self.groupBox_4.setTitle(_translate("InsperMatch", "Música", None))
        self.checkBox_61.setText(_translate("InsperMatch", "Eletônica", None))
        self.checkBox_62.setText(_translate("InsperMatch", "Reggae", None))
        self.checkBox_63.setText(_translate("InsperMatch", "Rock", None))
        self.checkBox_64.setText(_translate("InsperMatch", "Rap", None))
        self.checkBox_65.setText(_translate("InsperMatch", "Sertanejo", None))
        self.checkBox_66.setText(_translate("InsperMatch", "Samba", None))
        self.checkBox_67.setText(_translate("InsperMatch", "Pagode", None))
        self.checkBox_68.setText(_translate("InsperMatch", "Clássica", None))
        self.checkBox_69.setText(_translate("InsperMatch", "Funk", None))
        self.checkBox_70.setText(_translate("InsperMatch", "Jazz", None))
        self.checkBox_71.setText(_translate("InsperMatch", "Forró", None))
        self.checkBox_72.setText(_translate("InsperMatch", "MPB", None))
        self.groupBox_5.setTitle(_translate("InsperMatch", "Instrumentos", None))
        self.checkBox_85.setText(_translate("InsperMatch", "Percurssão", None))
        self.checkBox_86.setText(_translate("InsperMatch", "Saxofone", None))
        self.checkBox_87.setText(_translate("InsperMatch", "Violão", None))
        self.checkBox_88.setText(_translate("InsperMatch", "Gaita", None))
        self.checkBox_89.setText(_translate("InsperMatch", "Piano", None))
        self.checkBox_90.setText(_translate("InsperMatch", "Baixo", None))
        self.checkBox_91.setText(_translate("InsperMatch", "Banjo", None))
        self.checkBox_92.setText(_translate("InsperMatch", "Cavaquinho", None))
        self.checkBox_93.setText(_translate("InsperMatch", "Xilofone", None))
        self.checkBox_94.setText(_translate("InsperMatch", "Violino", None))
        self.checkBox_95.setText(_translate("InsperMatch", "Flauta", None))
        self.checkBox_96.setText(_translate("InsperMatch", "Ukulele", None))
        self.groupBox_6.setTitle(_translate("InsperMatch", "Entidades", None))
        self.checkBox_109.setText(_translate("InsperMatch", "Bateria Imperial", None))
        self.checkBox_110.setText(_translate("InsperMatch", "Revista Insper Post", None))
        self.checkBox_111.setText(_translate("InsperMatch", "Liga de Empreendedorismo", None))
        self.checkBox_112.setText(_translate("InsperMatch", "Sementes Culturais", None))
        self.checkBox_113.setText(_translate("InsperMatch", "Diretório Acadêmico", None))
        self.checkBox_114.setText(_translate("InsperMatch", "InFinance", None))
        self.checkBox_115.setText(_translate("InsperMatch", "AIESEC", None))
        self.checkBox_116.setText(_translate("InsperMatch", "Enactus", None))
        self.checkBox_117.setText(_translate("InsperMatch", "BemGasto", None))
        self.checkBox_118.setText(_translate("InsperMatch", "GAS", None))
        self.checkBox_119.setText(_translate("InsperMatch", "Atlética", None))
        self.checkBox_120.setText(_translate("InsperMatch", "Insper Jr", None))

