# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsperMatch.ui'
#
# Created: Thu May 28 13:42:22 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(561, 693)
        self.mdiArea = QtGui.QMdiArea(Form)
        self.mdiArea.setGeometry(QtCore.QRect(410, 10, 131, 151))
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 234, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout.addWidget(self.radioButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 266, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateEdit = QtGui.QDateEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit = QtGui.QTextEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 150, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 501, 401))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 101, 361))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_8 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_9 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_11 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_10 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_7 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_2.addWidget(self.checkBox)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 30, 109, 361))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_13 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.verticalLayout_3.addWidget(self.checkBox_13)
        self.checkBox_14 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.verticalLayout_3.addWidget(self.checkBox_14)
        self.checkBox_15 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.verticalLayout_3.addWidget(self.checkBox_16)
        self.checkBox_17 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.verticalLayout_3.addWidget(self.checkBox_18)
        self.checkBox_19 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.verticalLayout_3.addWidget(self.checkBox_19)
        self.checkBox_20 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.verticalLayout_3.addWidget(self.checkBox_20)
        self.checkBox_21 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.verticalLayout_3.addWidget(self.checkBox_21)
        self.checkBox_22 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.verticalLayout_3.addWidget(self.checkBox_22)
        self.checkBox_23 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.verticalLayout_3.addWidget(self.checkBox_23)
        self.checkBox_24 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.verticalLayout_3.addWidget(self.checkBox_24)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(260, 30, 101, 361))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_25 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.verticalLayout_4.addWidget(self.checkBox_25)
        self.checkBox_26 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.verticalLayout_4.addWidget(self.checkBox_26)
        self.checkBox_27 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.verticalLayout_4.addWidget(self.checkBox_27)
        self.checkBox_28 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.verticalLayout_4.addWidget(self.checkBox_28)
        self.checkBox_29 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.verticalLayout_4.addWidget(self.checkBox_29)
        self.checkBox_30 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.verticalLayout_4.addWidget(self.checkBox_30)
        self.checkBox_31 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.verticalLayout_4.addWidget(self.checkBox_31)
        self.checkBox_32 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.verticalLayout_4.addWidget(self.checkBox_32)
        self.checkBox_33 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.verticalLayout_4.addWidget(self.checkBox_33)
        self.checkBox_34 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.verticalLayout_4.addWidget(self.checkBox_34)
        self.checkBox_35 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.verticalLayout_4.addWidget(self.checkBox_35)
        self.checkBox_36 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.verticalLayout_4.addWidget(self.checkBox_36)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(380, 30, 101, 361))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_37 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.verticalLayout_5.addWidget(self.checkBox_37)
        self.checkBox_38 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.verticalLayout_5.addWidget(self.checkBox_38)
        self.checkBox_39 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.verticalLayout_5.addWidget(self.checkBox_39)
        self.checkBox_40 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.verticalLayout_5.addWidget(self.checkBox_40)
        self.checkBox_41 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.verticalLayout_5.addWidget(self.checkBox_41)
        self.checkBox_42 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.verticalLayout_5.addWidget(self.checkBox_42)
        self.checkBox_43 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.verticalLayout_5.addWidget(self.checkBox_43)
        self.checkBox_44 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.verticalLayout_5.addWidget(self.checkBox_44)
        self.checkBox_45 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.verticalLayout_5.addWidget(self.checkBox_45)
        self.checkBox_46 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.verticalLayout_5.addWidget(self.checkBox_46)
        self.checkBox_47 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.verticalLayout_5.addWidget(self.checkBox_47)
        self.checkBox_48 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.verticalLayout_5.addWidget(self.checkBox_48)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 600, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_2 = QtGui.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 600, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 640, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_3.setText(_translate("Form", "Sexo:", None))
        self.radioButton_2.setText(_translate("Form", "Masculino", None))
        self.radioButton.setText(_translate("Form", "Feminino", None))
        self.label_2.setText(_translate("Form", "Data de Nascimento:", None))
        self.label.setText(_translate("Form", "Nome:", None))
        self.comboBox.setItemText(0, _translate("Form", "Curso", None))
        self.comboBox.setItemText(1, _translate("Form", "Engenharia", None))
        self.comboBox.setItemText(2, _translate("Form", "Administração", None))
        self.comboBox.setItemText(3, _translate("Form", "Economia", None))
        self.groupBox.setTitle(_translate("Form", "Características", None))
        self.checkBox_3.setText(_translate("Form", "Futebol", None))
        self.checkBox_6.setText(_translate("Form", "Rugby", None))
        self.checkBox_8.setText(_translate("Form", "Volei", None))
        self.checkBox_9.setText(_translate("Form", "Handebol", None))
        self.checkBox_11.setText(_translate("Form", "Futsal", None))
        self.checkBox_12.setText(_translate("Form", "Xadrez", None))
        self.checkBox_10.setText(_translate("Form", "Tênis de Mesa", None))
        self.checkBox_7.setText(_translate("Form", "Jiu-Jitsu", None))
        self.checkBox_5.setText(_translate("Form", "Tênis", None))
        self.checkBox_4.setText(_translate("Form", "Natação", None))
        self.checkBox_2.setText(_translate("Form", "Basquete", None))
        self.checkBox.setText(_translate("Form", "Surf", None))
        self.checkBox_13.setText(_translate("Form", "Batata frita", None))
        self.checkBox_14.setText(_translate("Form", "Donuts", None))
        self.checkBox_15.setText(_translate("Form", "Lasanha", None))
        self.checkBox_16.setText(_translate("Form", "Comida Japonesa", None))
        self.checkBox_17.setText(_translate("Form", "Pizza", None))
        self.checkBox_18.setText(_translate("Form", "Esfiha", None))
        self.checkBox_19.setText(_translate("Form", "Feijoada", None))
        self.checkBox_20.setText(_translate("Form", "Cachorro-Quente", None))
        self.checkBox_21.setText(_translate("Form", "Risotto", None))
        self.checkBox_22.setText(_translate("Form", "Churrasco", None))
        self.checkBox_23.setText(_translate("Form", "Macarrão", None))
        self.checkBox_24.setText(_translate("Form", "Hamburger", None))
        self.checkBox_25.setText(_translate("Form", "Balada", None))
        self.checkBox_26.setText(_translate("Form", "Cervejada", None))
        self.checkBox_27.setText(_translate("Form", "Bar", None))
        self.checkBox_28.setText(_translate("Form", "Cinema", None))
        self.checkBox_29.setText(_translate("Form", "Restaurante", None))
        self.checkBox_30.setText(_translate("Form", "Casa Amigos", None))
        self.checkBox_31.setText(_translate("Form", "Parque", None))
        self.checkBox_32.setText(_translate("Form", "Livro", None))
        self.checkBox_33.setText(_translate("Form", "Soneca", None))
        self.checkBox_34.setText(_translate("Form", "Séries", None))
        self.checkBox_35.setText(_translate("Form", "Facebook", None))
        self.checkBox_36.setText(_translate("Form", "Shopping", None))
        self.checkBox_37.setText(_translate("Form", "Violão", None))
        self.checkBox_38.setText(_translate("Form", "Banjo", None))
        self.checkBox_39.setText(_translate("Form", "Cavaquinho", None))
        self.checkBox_40.setText(_translate("Form", "Bateria", None))
        self.checkBox_41.setText(_translate("Form", "Flauta", None))
        self.checkBox_42.setText(_translate("Form", "Piano", None))
        self.checkBox_43.setText(_translate("Form", "Violino", None))
        self.checkBox_44.setText(_translate("Form", "Baixo", None))
        self.checkBox_45.setText(_translate("Form", "Saxofone", None))
        self.checkBox_46.setText(_translate("Form", "Bongô", None))
        self.checkBox_47.setText(_translate("Form", "Xilofone", None))
        self.checkBox_48.setText(_translate("Form", "Pandeiro", None))
        self.label_4.setText(_translate("Form", "Bairro:", None))
        self.comboBox_2.setItemText(0, _translate("Form", "Morumbi", None))
        self.comboBox_2.setItemText(1, _translate("Form", "mooca", None))
        self.comboBox_2.setItemText(2, _translate("Form", "moema", None))
        self.pushButton.setText(_translate("Form", "Salvar", None))

